<a href="https://colab.research.google.com/github/murpunk/Programming_2023/blob/main/27_02_23_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Часть I

Прочитайте текст «User Guide “10 minutes to pandas”» (текст лекции) или 
https://pandas.pydata.org/docs/user_guide/10min.html и выполните команды из него в Jupyter/Google Colab.

In [1]:
import numpy as np
import pandas as pd

## Часть II

### 3. Создайте объект Series из словаря

In [2]:
s = pd.Series({
    "A": 4,
    "B": 5,
    "C": 7
})
s

A    4
B    5
C    7
dtype: int64

### 5. Выдать на экран представление данных массива (values) и его индекса (index). Обратиться по индексу к элементу Series и поменять его значение. Присвойте имя объекту Series (свойство name), и его индексу (index.name). Выведите его тип значений (dtype).

Выдача всех значений из массива данных с помощью values

In [3]:
s.values

array([4, 5, 7])

Выдача индексов массива данных с помощью index

In [4]:
s.index

Index(['A', 'B', 'C'], dtype='object')

Обращение к элементу массива по индексу

In [6]:
s.iloc[2]

7

Смена значения элемента массива по индексу

In [8]:
s.iloc[2] = 6

In [9]:
s

A    4
B    5
C    6
dtype: int64

Присвоение имени для Series при помощи свойства name

In [10]:
s.name = "Series from a dict"

Присвоение имени индекса с помощью index.name

In [13]:
s.index.name = "NI"

In [14]:
s

NI
A    4
B    5
C    6
Name: Series from a dict, dtype: int64

Вывести тип значений с помощью dtypes

In [16]:
s.dtypes

dtype('int64')

### 6. Создайте объект DataFrame из случайной матрицы numpy. При создании задайте ему индекс (с помощью атрибута index), например, присвойте список чисел.

Создание случайной матрицы numpy

In [18]:
q = np.random.randn(12).reshape(3, 4)
q

array([[-3.18612507e-02,  1.62535285e+00, -4.64214201e-01,
        -4.73081342e-01],
       [-7.94508713e-01, -9.04894684e-01, -5.99808424e-01,
         8.55126838e-01],
       [-2.02144299e+00, -4.84404360e-01,  1.54731435e-04,
         2.41810216e-01]])

Создание DataFrame из случайной матрицы numpy

Задать индекс новому DataFrame'у

In [26]:
dates = pd.date_range("20230227", periods=3)
dates

DatetimeIndex(['2023-02-27', '2023-02-28', '2023-03-01'], dtype='datetime64[ns]', freq='D')

In [31]:
r = pd.DataFrame(q, index = dates, columns = list("ABCD"))
r

A         B         C         D
2023-02-27 -0.031861  1.625353 -0.464214 -0.473081
2023-02-28 -0.794509 -0.904895 -0.599808  0.855127
2023-03-01 -2.021443 -0.484404  0.000155  0.241810

### 10. Выдать на экран представление данных в виде матрицы numpy (values), его индекса (index), столбцов (columns) и типы столбцов (dtypes).

Выдача данных в виде матрицы numpy с помощью values

In [28]:
r.values

array([[-3.18612507e-02,  1.62535285e+00, -4.64214201e-01,
        -4.73081342e-01],
       [-7.94508713e-01, -9.04894684e-01, -5.99808424e-01,
         8.55126838e-01],
       [-2.02144299e+00, -4.84404360e-01,  1.54731435e-04,
         2.41810216e-01]])

Выдача индекса с помощью index

In [29]:
r.index

DatetimeIndex(['2023-02-27', '2023-02-28', '2023-03-01'], dtype='datetime64[ns]', freq='D')

Выдача столбцов с помощью columns

In [32]:
r.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

Выдача типов столбцов с помощью dtypes

In [33]:
r.dtypes

A    float64
B    float64
C    float64
D    float64
dtype: object

### 11. Выдайте на экран информацию о созданном выше объект DataFrame: размерность (ndim, shape), количество элементов (size).


Выдача размерности DataFrame с помощью ndim

In [35]:
r.ndim

2

Выдача размера с помощью shape

In [36]:
r.shape

(3, 4)

Выдача количества элементов с помощью size

In [37]:
r.size

12

### 12. Обратиться к одному столбцу объект DataFrame: имя[имя столбца]. Выдать на экран представление данных этого столбца (values) и его индекса (index). Выведите на экран его имя (name) и его тип значений (dtype).

Обращение к одному столбцу DataFrame по его имени в квадратных скобках

In [38]:
r["B"]

2023-02-27    1.625353
2023-02-28   -0.904895
2023-03-01   -0.484404
Freq: D, Name: B, dtype: float64

Выдача представлений данных этого столбца с помощью values

In [40]:
r["B"].values

array([ 1.62535285, -0.90489468, -0.48440436])

Выдача индексов для этого столбца с помощью index

In [42]:
r["B"].index

DatetimeIndex(['2023-02-27', '2023-02-28', '2023-03-01'], dtype='datetime64[ns]', freq='D')

Выдача имени этого столбца по индексу

In [50]:
r.iloc[:, 1].name

'B'

Выдача типа столбца с помощью dtype

In [51]:
r["B"].dtype

dtype('float64')

### 18. Поменяйте порядок столбцов с помощью метода reindex.

In [54]:
r.reindex(columns = ["A", "D", "C", "B"])

A         D         C         B
2023-02-27 -0.031861 -0.473081 -0.464214  1.625353
2023-02-28 -0.794509  0.855127 -0.599808 -0.904895
2023-03-01 -2.021443  0.241810  0.000155 -0.484404

### 21. Вывести 3 первых строки из объекта DataFrame (метод head).

In [110]:
r.head(2)

A         B         C  D    E    F
2023-02-27 -0.318613  1.625353 -0.464214  5  one  1.0
2023-02-28 -7.945087 -0.904895 -0.599808  5  one  1.0

### 25. Выделить несколько столбцов, используя обращение по имени столбцов.

In [60]:
r.loc[:, ['B', 'C']]

B         C
2023-02-27  1.625353 -0.464214
2023-02-28 -0.904895 -0.599808
2023-03-01 -0.484404  0.000155

### 31. Выделить одно значение с помощью меток (метод at).

In [62]:
r.at[dates[1], "C"]

-0.5998084242780408

### 37. Используя метод isin, выбрать строки, удовлетворяющие некоторому условию.

In [63]:
r

A         B         C         D
2023-02-27 -0.031861  1.625353 -0.464214 -0.473081
2023-02-28 -0.794509 -0.904895 -0.599808  0.855127
2023-03-01 -2.021443 -0.484404  0.000155  0.241810

In [65]:
r["E"] = ["one", "one", "two"]

In [66]:
r

A         B         C         D    E
2023-02-27 -0.031861  1.625353 -0.464214 -0.473081  one
2023-02-28 -0.794509 -0.904895 -0.599808  0.855127  one
2023-03-01 -2.021443 -0.484404  0.000155  0.241810  two

In [69]:
r.isin(["one"])

A      B      C      D      E
2023-02-27  False  False  False  False   True
2023-02-28  False  False  False  False   True
2023-03-01  False  False  False  False  False

### 40. Установить сразу несколько значений в некотором срезе (loc).

In [72]:
r.loc[:, "D"] = np.array([5] * len(r))
r

A         B         C  D    E
2023-02-27 -0.031861  1.625353 -0.464214  5  one
2023-02-28 -0.794509 -0.904895 -0.599808  5  one
2023-03-01 -2.021443 -0.484404  0.000155  5  two

### 43. Удалить все столбцы, у которых есть не определенные значения (метод dropna).

In [97]:
r.loc[dates[0] : dates[1], "F"] = 1 # создаю дополнительный столбец, где не все строчки заполнены
r

A         B         C  D    E    F
2023-02-27  -0.318613  1.625353 -0.464214  5  one  1.0
2023-02-28  -7.945087 -0.904895 -0.599808  5  one  1.0
2023-03-01 -20.214430 -0.484404  0.000155  5  two  NaN

In [76]:
r.dropna(axis='columns') # удаляю столбец, где есть nan значения

A         B         C  D    E
2023-02-27 -0.031861  1.625353 -0.464214  5  one
2023-02-28 -0.794509 -0.904895 -0.599808  5  one
2023-03-01 -2.021443 -0.484404  0.000155  5  two

### 49. Увеличить все значения в одном столбце DataFrame в 10 раз.

In [77]:
r["A"] *= 10

In [78]:
r

A         B         C  D    E    F
2023-02-27  -0.318613  1.625353 -0.464214  5  one  1.0
2023-02-28  -7.945087 -0.904895 -0.599808  5  one  1.0
2023-03-01 -20.214430 -0.484404  0.000155  5  two  NaN

### 53. Выведите сумму, среднее и минимальное значения.

In [80]:
t = r[:] # создаю копию DataFrame'а, чтобы не портить изначальный DataFrame r

In [81]:
t

A         B         C  D    E    F
2023-02-27  -0.318613  1.625353 -0.464214  5  one  1.0
2023-02-28  -7.945087 -0.904895 -0.599808  5  one  1.0
2023-03-01 -20.214430 -0.484404  0.000155  5  two  NaN

In [87]:
t = t.drop(['E', "F"], axis=1) # удаляю столбец с текстовыми данными и столбец с неопределёнными значениями

In [88]:
t

A         B         C  D
2023-02-27  -0.318613  1.625353 -0.464214  5
2023-02-28  -7.945087 -0.904895 -0.599808  5
2023-03-01 -20.214430 -0.484404  0.000155  5

Сумма по строчкам с помощью axis = 1

In [90]:
t.sum(axis = 1)

2023-02-27     5.842526
2023-02-28    -4.449790
2023-03-01   -15.698680
Freq: D, dtype: float64

Сумма по столбцам с помощью axis = 0

In [91]:
t.sum(axis = 0)

A   -28.478130
B     0.236054
C    -1.063868
D    15.000000
dtype: float64

Сумма всех элементов с помощью values.sum()

In [94]:
t.values.sum()

-14.30594364420132

Выдача среднего значения по строчкам mean(), axis = 1

In [98]:
t.mean(axis = 1)

2023-02-27    1.460632
2023-02-28   -1.112448
2023-03-01   -3.924670
Freq: D, dtype: float64

Выдача среднего значения по столбцам mean(), axis = 0

In [99]:
t.mean(axis = 0)

A   -9.492710
B    0.078685
C   -0.354623
D    5.000000
dtype: float64

Среднее значение по всем значениям DataFrame'а

In [100]:
t.values.mean()

-1.19216197035011

Выдача минимального значения в строчке, axis = 1

In [101]:
t.min(axis = 1)

2023-02-27    -0.464214
2023-02-28    -7.945087
2023-03-01   -20.214430
Freq: D, dtype: float64

Выдача минимального значения в столбцах, axis = 0

In [103]:
t.min()

A   -20.214430
B    -0.904895
C    -0.599808
D     5.000000
dtype: float64

Выдача минимального значения по всему DataFrame'у

In [104]:
t.values.min()

-20.214429919613103

### 58. Применить минимаксную нормализацию к одному столбцу DataFrame. Для этого все элементы столбца преобразовать по формуле: $2 * \frac{x - min}{max - min} - 1$, где min, max – минимум и максимум в этом столбце.

In [116]:
t

A         B         C  D
2023-02-27  1.000000  1.625353 -0.464214  5
2023-02-28  0.233359 -0.904895 -0.599808  5
2023-03-01 -1.000000 -0.484404  0.000155  5

In [115]:
#for i in t["A"]:
t["A"] = 2 * (t["A"] - t["A"].min()) / (t["A"].max() - t["A"].min()) - 1

### 60. Запишите DataFrame в файл формата cvs (метод to_csv).

In [109]:
r.to_csv("DataFrame T.csv")