<a href="https://colab.research.google.com/github/murpunk/Programming_2023/blob/main/Numpy_20_02_23.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 4. Создать вектор с помощью функции zeros

In [ ]:
import numpy as np

In [ ]:
a = np.zeros((5,), dtype = int)

In [ ]:
a

array([0, 0, 0, 0, 0])

## 7. Создайте двумерный массив случайных чисел с помощью uniform модуля random

Нормальное распределение из промежутка [-10, 10], всего 5 чисел

In [ ]:
a = np.random.uniform(-10, 10, size = 5)

In [ ]:
a

array([ 6.44899946,  9.89978255,  2.66600166, -6.72375715,  5.74524641])

## 9. Выдайте на экран информацию о созданном выше массиве: тип (dtype), размерность (ndim, shape), количество элементов (size), itemsize, nbytes.

In [ ]:
a.dtype # тип данных в массиве

dtype('float64')

In [ ]:
a.ndim # размерность массива, в данном случае у меня вектор

1

In [ ]:
a.shape # размер массива, у меня пять элементов в строке

(5,)

In [ ]:
a.size # показывает количество элементов в массиве

5

In [ ]:
a.itemsize # сколько байт на один элемент

8

In [ ]:
a.nbytes # сколько байт на все элементы массива

40

## 10. С помощью срезов выделите несколько элементов в массиве и поменяйте их значения.

In [ ]:
a = np.arange(12)

In [ ]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
b = a[-1]

In [ ]:
b

11

In [ ]:
a[a == 8] = 20

In [ ]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7, 20,  9, 10, 11])

In [ ]:
a[:12:2] = -3

In [ ]:
a

array([-3,  1, -3,  3, -3,  5, -3,  7, -3,  9, -3, 11])

## 11. Найти результаты арифметических операций для 2 массивов (или числа и массива). Используйте операции или функции numpy (т.е., например, “+” или “np.add”). Вычислите еще любые две функции от массивов

In [ ]:
d = np.arange(15).reshape(5, 3)
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
d

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [ ]:
e = np.arange(15).reshape(5, 3)

In [ ]:
e = e**2

In [ ]:
e

array([[  0,   1,   4],
       [  9,  16,  25],
       [ 36,  49,  64],
       [ 81, 100, 121],
       [144, 169, 196]], dtype=int32)

In [ ]:
d + e

array([[  0,   2,   6],
       [ 12,  20,  30],
       [ 42,  56,  72],
       [ 90, 110, 132],
       [156, 182, 210]])

In [ ]:
np.add(d, e)

array([[  0,   2,   6],
       [ 12,  20,  30],
       [ 42,  56,  72],
       [ 90, 110, 132],
       [156, 182, 210]])

In [ ]:
d - e

array([[   0,    0,   -2],
       [  -6,  -12,  -20],
       [ -30,  -42,  -56],
       [ -72,  -90, -110],
       [-132, -156, -182]])

In [ ]:
np.subtract(d, e)

array([[   0,    0,   -2],
       [  -6,  -12,  -20],
       [ -30,  -42,  -56],
       [ -72,  -90, -110],
       [-132, -156, -182]])

In [ ]:
d * e

array([[   0,    1,    8],
       [  27,   64,  125],
       [ 216,  343,  512],
       [ 729, 1000, 1331],
       [1728, 2197, 2744]])

In [ ]:
np.multiply(d, e)

array([[   0,    1,    8],
       [  27,   64,  125],
       [ 216,  343,  512],
       [ 729, 1000, 1331],
       [1728, 2197, 2744]])

## 13. Вычислите расстояние между двумя векторами

In [ ]:
f = np.arange(3)
f

array([0, 1, 2])

In [ ]:
g = np.arange(7, 13, 2)
g

array([ 7,  9, 11])

sqrt(sum(fi-gi)^2)
или
norm(f-g)

Первый способ: через евклидово расстояние

In [ ]:
s = np.sum((f - g)**2)
s

194

In [ ]:
dist1 = np.sqrt(s)

In [ ]:
dist1

13.92838827718412

Второй способ: через норму вектора

In [ ]:
dist2 = np.linalg.norm(f - g)

In [ ]:
dist2

13.92838827718412

## 19. Создайте 2 матрицы одинакового размера. Найти результаты арифметических операций для 2 матриц. Кроме поэлементного умножения “*”, вычислите еще  произведение матриц с помощью функции “np.dot”.

In [ ]:
m = np.arange(12).reshape(3,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
n = np.arange(14,26).reshape(3,4)
n

array([[14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25]])

## 23. Найдите обратную матрицу к квадратной матрице

## 26. Агрегирование. Определите произвольный массив. Найдите для него следующие величины (можно по одной из осей или для всего массива): произведение, стандартное отклонение и индекс минимального значения

## 30. Сравнения, маски и булева логика. Определите произвольный массив. Определите, все ли они положительные

## 33. Определите произвольную матрицу. Измерьте время работы кода для больших матриц (1000, 10000 и т.д. строк). Сделайте это же задание, используя стандартные средства Python, сравните время работы. Посчитайте среднее значение в ее первом столбце. И добавьте в конец матрицы новый столбец из этих средних значений. 

## 36. Определите произвольный двумерный массив. Отсортируйте в матрице строки

## 41. .Сохраните массив в двоичный файл (np.save) и прочитайте его из файла (np.load)