<a href="https://colab.research.google.com/github/murpunk/Programming_2023/blob/main/%D0%9F%D0%BE%D0%BB%D0%BD%D0%BE%D1%81%D0%B2%D1%8F%D0%B7%D0%BD%D0%B0%D1%8F_%D1%81%D0%B5%D1%82%D1%8C_%D0%9C%D0%B5%D1%82%D0%BE%D0%B4_%D0%BE%D0%B1%D1%80%D0%B0%D1%82%D0%BD%D0%BE%D0%B3%D0%BE_%D1%80%D0%B0%D1%81%D0%BF%D1%80%D0%BE%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B5%D0%BD%D0%B8%D1%8F_%D0%BE%D1%88%D0%B8%D0%B1%D0%BA%D0%B8_21_09_23.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 0. Источники

1. К.В.Воронцов МФТИ Лекция 3. Искусственные нейронные сети: градиентные методы оптимизации https://www.youtube.com/watch?v=e9wOnPdN8tY (16–41 мин. – обрат. распр. ошиб.; далее – оптимизации метода).
2. Евгений Соколов Основы глубинного обучения. НИИ ВШЭ. Лекция 2. Обратное распространение ошибки. Сверточные сети.
https://www.youtube.com/watch?v=2fPB3Je7E98
3. Пойнтер Ян. Программируем с PyTorch: Создание приложений глубокого обучения. — СПб.: Питер, 2020. — 256 с.
4. Стивенс Эли, Антига Лука, Виман Томас. PyTorch. Освещая глубокое обучение. — СПб.: Питер, 2022. — 576 с.

# Задание 1

Полносвязная сеть. Метод обратного распространения ошибки (см. [1] К.В.Воронцов или [2] Е.Соколов). Или другие книги и лекции.

Нейросеть, в которой есть только линейные слои и функции активации, называют **полносвязной** (fully connected) нейронной сетью, или **многослойным перцептроном** (multilayer perceptron, MLP).

**Линейный слой** (linear layer, dense layer) — линейное преобразование над входящими данными.

**Функция активации** (activation function) — нелинейное преобразование, поэлементно применяющееся к пришедшим на вход данным. Благодаря функциям активации нейронные сети способны порождать более информативные признаковые описания, преобразуя данные нелинейным образом. Может использоваться, например, ReLU (rectified linear unit) или уже знакомая вам из логистической регрессии сигмоида.

Полносвязные нейросети работают лучше, чем простые нейросети.

Применение нейронной сети к данным (вычисление выхода по заданному входу) часто называют **прямым проходом**, или же forward propagation (forward pass). На этом этапе происходит преобразование исходного представления данных в целевое и последовательно строятся промежуточные (внутренние) представления данных — результаты применения слоёв к предыдущим представлениям. Именно поэтому проход называют прямым.

При **обратном проходе**, или же backward propagation (backward pass), информация (обычно об ошибке предсказания целевого представления) движется от финального представления (а чаще даже от функции потерь) к исходному через все преобразования. Механизм обратного распространения ошибки, играющий важнейшую роль в обучении нейронных сетей, как раз предполагает обратное движение по вычислительному графу сети.

**Метод обратного распространения ошибки** (англ. backpropagation) — метод обучения нейронных сетей, который используется при обновлении весов полносвязной сети.

Основная идея этого метода состоит в распространении сигналов ошибки от выходов сети к её входам, в направлении, обратном прямому распространению сигналов в обычном режиме работы.

# Задание 2

Введение в PyTorch (см. книги [3], [4]). Прочитайте стр.13–37 книги [3]. Разберите и выполните команды PyTorch из книги (стр. 33–37).


Тензор — это контейнер для чисел и набор правил для преобразования тензоров. По сути это многомерные массивы. Тензор имеет ранг, показывающий его размерное пространство.

In [1]:
import torch

In [2]:
x = torch.tensor([[0,0,1],[1,1,1],[0,0,0]]) # создали тензор из списка
x

tensor([[0, 0, 1],
        [1, 1, 1],
        [0, 0, 0]])

In [4]:
x[0][0] = 5 # изменили элемент в тензоре, используя методы стандартного индексирования
x

tensor([[5, 0, 1],
        [1, 1, 1],
        [0, 0, 0]])

In [5]:
torch.zeros(2,2) # генерация тензора, заполненная нулями

tensor([[0., 0.],
        [0., 0.]])

In [7]:
# операция сложения тензоров
torch.ones(1,2) + torch.ones(1,2) # в книге опечатка: вместо torch написано tensor

tensor([[2., 2.]])

In [23]:
y = torch.rand(1) # rand создаёт случайный тензор. в этом примере размерность 0, то есть это число
y

tensor([0.0305])

In [30]:
torch.rand(1).item() # с помощью item извлекаются значения у тензоров ранга 0 (то есть чисел)

0.6044024229049683

In [11]:
cpu_tensor = torch.rand(2) # тензоры находятся в центральном процессоре
cpu_tensor.device

device(type='cpu')

In [12]:
gpu_tensor = cpu_tensor.to("cuda") # не переносится в другой процессор. ошибка: Found no NVIDIA driver on your system.
gpu_tensor.device

RuntimeError: ignored

In [13]:
torch.rand(2,2).max() # находим максимальный элемент в тензоре

tensor(0.8205)

In [14]:
torch.rand(2,2).max().item() # находим максимальный элемент в тензоре 1D

0.880636990070343

In [15]:
long_tensor = torch.tensor([[0,0,1],[1,1,1],[0,0,0]]) # находим тип тензора
long_tensor.type()

'torch.LongTensor'

In [17]:
# изменяем тип тензора
float_tensor = torch.tensor([[0,0,1],[1,1,1],[0,0,0]]).to(dtype=torch.float32)
float_tensor.type()


'torch.FloatTensor'

In [20]:
flat_tensor = torch.rand(784) # с помощью reshape или view можно изменить сам тензор
viewed_tensor = flat_tensor.view(1,28,28)
viewed_tensor.shape

torch.Size([1, 28, 28])

In [21]:
# форма изменённого тензора должна иметь то же количество элементов, что и оригинал
# например, flat_tensor.reshape(3,28,28) вызовет ошибку
reshaped_tensor = flat_tensor.reshape(1,28,28)
reshaped_tensor.shape

torch.Size([1, 28, 28])

In [22]:
hwc_tensor = torch.rand(640, 480, 3)
chw_tensor = hwc_tensor.permute(2,0,1) # изменяются размеры тензора
chw_tensor.shape

torch.Size([3, 640, 480])

# Пример

In [ ]:
#conda install pytorch torchvision -c pytorch
# или
#pip install torch

In [ ]:
import torch

In [ ]:
x = torch.rand(5, 3)
x

tensor([[0.5918, 0.2730, 0.3234],
        [0.1913, 0.8521, 0.1116],
        [0.9918, 0.6873, 0.8988],
        [0.4777, 0.0850, 0.5035],
        [0.5774, 0.5755, 0.4151]])

In [ ]:
x.shape

torch.Size([5, 3])

In [ ]:
# Тензор способный хранить производные: requires_grad = True
w = torch.rand(1, requires_grad = True)
b = torch.rand(1, requires_grad = True)
print(w, b)

tensor([0.0647], requires_grad=True) tensor([0.7182], requires_grad=True)


In [ ]:
print(w.grad)

None


In [ ]:
x = torch.tensor([2, 3, 4, -1, 0, -2], dtype=torch.float32)
y = torch.tensor([1, 1, 1, -1, -1, -1], dtype=torch.float32)

In [ ]:
y_pred = w * x + b
loss = torch.mean((y_pred - y) ** 2)
loss.backward()

In [ ]:
print(w.data, b.data)
print(w.grad, b.grad)

tensor([0.0647]) tensor([0.7182])
tensor([-1.8305]) tensor([1.5658])


In [ ]:
y_pred.data

tensor([0.8476, 0.9123, 0.9769, 0.6535, 0.7182, 0.5889])